name: Update Instagram Gallery

on:
  workflow_dispatch:   # Allows manual trigger
  schedule:
    # Runs every day at 12:00 UTC
    - cron: '0 12 * * *'

jobs:
  update_gallery:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script to fetch Instagram photos
      run: python .github/scripts/fetch_instagram.py

    - name: Configure git and commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gallery.html
        git diff --exit-code || git commit -m "Update gallery with new Instagram photos"
        git push https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
